go back to separated travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -29,6 +29,86 @@ branches:
 
 stages:
   - name: Greenkeeper
+    if: branch =~ ^greenkeeper\/
+  - name: Test
+  - name: Deploy Data
+    if: branch = master AND type != pull_request
+  - name: Build + Deploy App
+
+
+
+#
+# Definitions of dictionaries that are used by the machines below
+#
+
+x-definitions:
+  - &base
+    before_install:
+      # print some travis debugging info
+      - echo "Now testing on $TRAVIS_OS_NAME"
+      - echo "Travis branch is $TRAVIS_BRANCH"
+      - echo "Travis is in pull request $TRAVIS_PULL_REQUEST"
+      - echo "Build triggered by $TRAVIS_EVENT_TYPE"
+
+      # force the ruby we want
+      - echo "Using ruby $TRAVIS_RUBY_VERSION (ruby -v says $(ruby -v))"
+      - rvm use $TRAVIS_RUBY_VERSION --install --binary --create
+      - echo "ruby -v is now $(ruby -v)"
+      - gem install bundler
+
+      # force a consistent node version
+      - echo "Using node $TRAVIS_NODE_VERSION (node -v says $(node -v))"
+      - nvm install "$TRAVIS_NODE_VERSION"
+      - nvm use "$TRAVIS_NODE_VERSION"
+      - echo "node -v is now $(node -v)"
+
+      # travis doesn't install yarn automatically on osx
+      - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install yarn --without-node; fi
+
+    install:
+      # install packages (if the first fails, try once more)
+      - yarn || yarn
+
+      # install fastlane (if at first you don't succeed, try once more)
+      - bundle install || bundle install
+
+    before_script:
+      # ensure the env file exists and fill it out
+      - touch .env.js
+      - echo "export const GOOGLE_CALENDAR_API_KEY = '$GCAL_KEY'" >> .env.js
+      - echo "export const GOOGLE_MAPS_API_KEY = '$GMAPS_KEY'" >> .env.js
+
+      # disable npm wrapper for npm scripts
+      - echo "loglevel=silent" >> .npmrc
+
+    after_script:
+      - npm run danger -- --id $task
+
+    before_cache:
+      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
+      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
+      - rm -rf $TMPDIR/jest_preprocess_cache
+
+  - &js
+    <<: *base
+    os: linux
+    sudo: false
+    distro: trusty
+    language: node_js
+    node_js: $TRAVIS_NODE_VERSION
+    install: yarn || yarn
+    before_script:
+      - echo "loglevel=silent" >> .npmrc
+      - mkdir -p logs/
+      - set -o pipefail
+    env: [task=JS-unknown]
+
+  - &simplejs
+    os: linux
+    sudo: false
+    distro: trusty
+    language: node_js
+    node_js: $TRAVIS_NODE_VERSION
 
 
 jobs:
@@ -36,29 +116,104 @@ jobs:
   # To skip the default step, use `step_name: skip`.
   include:
     # Run greenkeeper stuff
-    - os: linux
-      sudo: false
-      distro: trusty
-      language: node_js
-      node_js: $TRAVIS_NODE_VERSION
-      install: yarn || yarn
+    - <<: *simplejs
+      stage: Greenkeeper
       env: [task=GREENKEEPER]
+      install: npm install -g greenkeeper-lockfile@1
       before_script: mkdir -p logs/
-      script:
+      script: greenkeeper-lockfile-update
+      after_script:
+        - greenkeeper-lockfile-upload
         - npm run danger -- --id $task
 
-    - os: linux
-      sudo: false
-      distro: trusty
-      language: node_js
-      node_js: $TRAVIS_NODE_VERSION
-      install: yarn || yarn
+    # Do node "tests"
+    - <<: *js
+      stage: Test
+      env: [task=JS-flow]
+      script:
+        - npm run bundle-data
+        - npm run flow -- check --quiet | tee logs/flow
+
+    - <<: *js
+      stage: Test
+      env: [task=JS-prettier]
+      script:
+        # Ensure prettiness
+        - npm run prettier
+        - if ! git diff --quiet ./*.js source/; then
+            git diff ./*.js source/ > logs/prettier;
+          fi
+
+    - <<: *js
+      stage: Test
+      env: [task=JS-lint]
+      script:
+        - npm run lint | tee logs/eslint
+
+    - <<: *js
+      stage: Test
       env: [task=JS-data]
-      before_script: mkdir -p logs/
       script:
         - npm run validate-data -- --quiet | tee logs/validate-data
         - npm run validate-bus-data | tee logs/validate-bus-data
-        - npm run danger -- --id $task
+
+    - <<: *js
+      stage: Test
+      env: [task=JS-jest]
+      before_install: npm install -g coveralls
+      script:
+        - npm run bundle-data
+        - npm run test -- --coverage 2>&1 | tee logs/jest
+      after_success: coveralls < ./coverage/lcov.info
+
+    # Deploy the gh-pages data
+    - <<: *simplejs
+      stage: Deploy Data
+      env: [task=GH_PAGES]
+      install: yarn || yarn
+      script: npm run bundle-data
+      deploy:
+        provider: pages
+        skip_cleanup: true
+        github_token: $GITHUB_PAGES_TOKEN
+        local_dir: docs/
+
+    # Build/deploy the Android binary
+    - <<: *base
+      stage: Build + Deploy
+      os: linux
+      sudo: required
+      distro: trusty
+      language: android
+      env: [task=ANDROID]
+      android:
+        components:
+          - tools
+          - platform-tools
+          - build-tools-23.0.1
+          - build-tools-23.0.2
+          - build-tools-25.0.0
+          - build-tools-25.0.1
+          - build-tools-25.0.2
+          - build-tools-25.0.3
+          - build-tools-26.0.1
+          - android-23
+          - android-25
+          - android-26
+          - extra-android-m2repository
+          - extra-google-m2repository
+      script:
+        - bundle exec fastlane android ci-run
+
+    # Build/deploy the iOS binary
+    - <<: *base
+      stage: Build + Deploy
+      os: osx
+      language: objective-c
+      osx_image: xcode9
+      env: [task=IOS]
+      script:
+        - bundle exec fastlane ios ci-run
 
 cache:
   bundler: true
