set up detox for android?

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -376,7 +376,7 @@ jobs:
             ./android/app/src/main/res/
           key: ${{ steps.jsbundle-cache.outputs.cache-primary-key }}
 
-  android:
+  android-build:
     name: Build for Android
     needs: [jest, eslint, android-bundle, cache-npm-linux]
     runs-on: ubuntu-22.04
@@ -440,6 +440,74 @@ jobs:
               repo: context.repo.repo,
               body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
             })
+
+  android-detox:
+    name: Detox E2E for Android
+    needs: [cache-npm-linux, android-bundle, android-build]
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        android_sdk: ['21', '33']
+    env:
+      android_emulator: pixel_4
+    steps:
+      - uses: actions/checkout@v3.3.0
+
+      - uses: actions/setup-java@v3
+        with:
+          distribution: ${{ env.java_distribution }}
+          java-version: ${{ env.java_version }}
+
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ env.node_version }}
+
+      - name: Restore node_modules cache
+        uses: actions/cache/restore@v3
+        id: node-cache
+        with:
+          path: node_modules/
+          key: ${{ needs.cache-npm-linux.outputs.cache-key }}
+
+      - name: Download Android Emulator Image SDK-${{ matrix.android_sdk }}
+        run: sdkmanager --install "system-images;android-${{ matrix.android_sdk }};google_apis;x86_64"
+
+      - name: Create AVD ${{ env.android_emulator }}
+        run: avdmanager --verbose create avd --force --name "${{ env.android_emulator }}" --device "Pixel 4" -k 'system-images;android-${{ matrix.android_sdk }};google_apis;x86_64'
+
+      - name: List AVDs
+        run: $ANDROID_HOME/emulator/emulator -list-avds
+
+      - name: Launch Android Emulator
+        timeout-minutes: 10
+        continue-on-error: true
+        shell: bash
+        run: |
+          # Start emulator
+          $ANDROID_SDK_ROOT/emulator/emulator '@${{ env.android_emulator }}' -no-audio -no-boot-anim -no-window -use-system-libs 2>&1 >/dev/null &
+
+          # Wait for emulator
+          max_retry=10
+          counter=0
+          until adb shell getprop sys.boot_completed; do
+            sleep 10
+            [[ counter -eq $max_retry ]] && echo "Failed to start the emulator!" && exit 1
+            counter=$((counter + 1))
+          done
+
+      - name: Run the Detox tests
+        run: |
+          npm start &
+          npx detox test e2e --configuration android.release --headless --record-logs failing --record-videos failing --record-performance all --capture-view-hierarchy enabled --take-screenshots failing
+
+      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
+        if: always()
+        with:
+          name: detox-android
+          path: artifacts/
+
+      - name: Stop the emulator
+        run: adb emu kill
 
   ios-build:
     name: Build for iOS
